name: Build and push Docker images

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-app
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: read
      packages: write

    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,arm'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set values for tagging Docker images (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        id: main_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.head_ref || github.ref_name }}
            type=raw,value=commit-${{ github.sha }}-${{ github.head_ref || github.ref_name }}
            type=raw,value=latest

      - name: Set values for tagging Docker images (other branches)
        if: ${{ github.ref != 'refs/heads/main' }}
        id: branch_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.head_ref || github.ref_name }}
            type=raw,value=commit-${{ github.sha }}-${{ github.head_ref || github.ref_name }}

      - name: Build and push Docker image to GitHub registry (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          cache-from: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.head_ref || github.ref_name }}'
          push: true
          tags: ${{ steps.main_meta.outputs.tags }}

      - name: Build and push Docker image to GitHub registry (other branches)
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          cache-from: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.head_ref || github.ref_name }}'
          push: true
          tags: ${{ steps.branch_meta.outputs.tags }}
